"""initial migration

Revision ID: 0983324c39b7
Revises: 
Create Date: 2023-10-05 12:58:01.001596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0983324c39b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_roles',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('modified_at', sa.DateTime(), nullable=False),
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('persons',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('modified_at', sa.DateTime(), nullable=False),
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('birth', sa.Date(), nullable=False),
                    sa.Column(
                        'gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'profile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('modified_at', sa.DateTime(), nullable=False),
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column(
                        'person_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('userroles',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('modified_at', sa.DateTime(), nullable=False),
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'role_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userroles')
    op.drop_table('users')
    op.drop_table('persons')
    op.drop_table('auth_roles')
    # ### end Alembic commands ###
